### ISSUE TITLE
Typo in post editor

### ISSUE THREAD

**Issue by uberoverlord** [the8/the8.github.io#1]
When credentials deemed incorrect it says "401: Bad credentials
If you are using two-factor-auth, you will ahve to create a personal access token with "repo" permissions and use this instead of your password." have is spelt incorrectly as "ahve".

**Comment by the8** [comment]
FIxed (I removed the form :wink:) .. I found a better way to create new posts from the CLI; check out Octopress 3.0 :grinning:
